module.exports = {
  Misc: {
    style: [
      'appearance',
      'content',
      'clip',
      'clipPath',
      'counterReset',
      'counterIncrement',
      'resize',
      'userSelect',
      'navIndex',
      'navUp',
      'navRight',
      'navDown',
      'navLeft',
      'pointerEvents',
      'quotes',
      'touchAction',
      'willChange',
      'zoom',
      'fill',
      'fillRule',
      'clipRule',
      'stroke',
    ],
    text: 'Misc',
  },
};
